### ISSUE TITLE
Mod Integration with Easy NPC (Forge)

### ISSUE THREAD

**Issue by MarkusBordihn** [Flemmli97/SimpleQuests#13]
### Suggestions

Dear mod developer,
first of all I really like your mod and it's a shame that it was going under my radar a long time.
I just want to let you know that I'm working on a feature to allow to use your simple quest mod seamless with the Easy NPC (https://github.com/MarkusBordihn/BOs-Easy-NPC) mod.

For this reason I wonder if you could help me with the following two parts from your side:

- Could you provide my a simple example (1-2 lines) for an language file. I took a look at `common/src/resources/data/simplequests/lang`  but was unable to find any example file. :(
- Do you have any plan's to upgrade your mod to 1.19.3 and maybe 1.19.4 so that I could run corresponding tests with my mod on my side?

Thanks again for the great work.

**Comment by Flemmli97** [comment]
`common/src/resources/data/simplequests/lang` should only be used if you want to provide default lang to the mod.
you just copy the `simplequest/lang/en_us.json` lang file in the config directory into it and apply changes.

else just either change the config lang file directly or copy it to a different name and change the used lang in the main config file

**Comment by Flemmli97** [comment]
closing it since everything seems to be addressed
