### ISSUE TITLE
[Feature Request]: adding a enable command

### ISSUE THREAD

**Issue by negapli** [Flemmli97/SimpleQuests#3]
### Suggestions

If the quest is disable it can't be accepted or show in the quest menu, but if the command "/simplequest enable" is trigger the quest is available for the /simplequests accept and in the quest menu

Making a enable command for enabling a disable quest like : /simplequest enable example:quest
Making a "disable" key in the json file, false by default

### Solution

>{
  "loot_table": "minecraft:chests/jungle_temple",
  "repeat_delay": 36000,
  "task": "Slay mobs",
 "disable": true,
  "entries": {
    "zombies": {
      "entity": "minecraft:zombie",
      "amount": 12,
      "id": "simplequests:entity"
    },
    "skeleton": {
      "entity": "minecraft:skeleton",
      "amount": 10,
      "id": "simplequests:entity"
    },
    "rottenflesh": {
      "ingredient": {
          "item": "minecraft:rotten_flesh"
      },
      "amount": 8,
      "id": "simplequests:ingredient"
    },
    "xp": {
      "amount": 5,
      "id": "simplequests:xp"
    }
  }
}

**Comment by Flemmli97** [comment]
is this meant to be global? aka if that command is used the quest will be enabled for everyone?

**Comment by negapli** [comment]
global or just for a specfic player like : /simplequest enable [player or @a @e...] test:test
