### ISSUE TITLE
[Feature Request]: JourneyMap waypoint integration

### ISSUE THREAD

**Issue by Steveplays28** [Flemmli97/SimpleQuests#5]
### Suggestions

It'd be nice if you could define a JourneyMap (temporary) waypoint that the player has to go to, for their current quest, and for the next quest.
FYI JourneyMap has normal and temporary waypoints. It would probably be nicer to use temporary waypoints for quests, since they disappear when you get within a specified distance (set in JourneyMap config, default=4 blocks)

### Solution

You could use the [JourneyMap API](https://www.curseforge.com/minecraft/mc-mods/journeymap-api) to implement this feature

**Comment by Flemmli97** [comment]
1. that api is outdated
2. journeymap is client side only and they dont have any packets or anything so i cant do anything from the server
3. its closed source arr
as such. no this feature will not be added (or rather cant)

**Comment by Steveplays28** [comment]
Fair enough, thanks for taking a look.
I didn't look into their API for more than like 2 seconds so I didn't notice it was outdated. mb.
